# Generated by Django 3.2.15 on 2022-09-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizeranking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='ranking',
            field=models.IntegerField(default=-1),
        ),
    ]
