# Generated by Django 3.2.15 on 2022-09-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizeranking_app', '0002_rankingmodel_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='ranking',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
