# Generated by Django 3.2.15 on 2022-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizeranking_app', '0003_auto_20220924_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingmodel',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
